services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    command: >
      sh -c "ollama serve &
             echo 'Aguardando o servidor Ollama...';
             while ! ollama list; do sleep 1; done;
             echo 'Servidor Ollama está pronto.';
             if ! ollama list | grep deepseek-r1; then
               echo 'Baixando o modelo deepseek-r1...';
               ollama pull deepseek-r1;
             fi;
             wait -n;"

volumes:
  postgres_data:
  redis_data:
  ollama_models: